ReviewList complete, ReviewSort complete
FEC-CLL/FEC pull request #28
Opened 2023-05-10 07:48 UTC by jkrav07

2023-05-10 08:11 UTC, jkrav07 commented
Cannot pass Test chec:
Two tests are failing in the main branch:
  ● Related Products and Outfits › Should render related products 
 ● Related Products and Outfits › Should render outfits list

2023-05-10 21:17 UTC, mellava commented on client/src/components/RatingsAndReviews/AddReview.jsx
> +/* eslint-disable no-unused-vars */
Should delete any unused variables instead of using eslint-disable no-unused-vars

2023-05-10 21:19 UTC, mellava commented on client/src/components/RatingsAndReviews/AddReview.jsx
> +/* eslint-disable react/prop-types */
Should keep eslint rule to disable react/prop-types

2023-05-10 21:20 UTC, mellava commented on client/src/components/RatingsAndReviews/Review.jsx
> +/* eslint-disable jsx-a11y/alt-text */
jsx-a11y/alt-text not necessary

2023-05-10 21:22 UTC, mellava commented on client/src/components/RatingsAndReviews/ReviewHelpfulness.jsx
> +/* eslint-disable jsx-a11y/no-noninteractive-element-interactions */
sx-a11y/click-events-have-key-events and jsx-a11y/no-noninteractive-element-interactions not necessary

2023-05-10 21:35 UTC, mellava requested changes
Eslint disables may not be needed.

2023-05-11 02:21 UTC, mellava approved these changes

2023-05-11 02:21 UTC, merged